### ISSUE TITLE
Cancel order results in NoMethodError: undefined method `keys' for <order id>:String

### ISSUE THREAD

**Issue by TimothyClayton** [shideneyu/kraken_client#15]
The documentation example shows passing an order id to `#cancel_order`:
`client.private.cancel("SOME-ORDER-ID")`  

This raises the error in the title. I figured I needed to pass `txid: "SOME-ORDER-ID"`, which worked, but did return the following warning message, due to the success response from the API of `#<Hashie::Mash count=1>`:  

`"You are setting a key that conflicts with a built-in method Hashie::Mash#count defined in Enumerable. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method."`  
 
I'm not sure how much of an issue this is as the cancel worked when passing `txid: "SOME-ORDER-ID"`

**Comment by shideneyu** [comment]
Thank you for the report, it has been fixed in Version 1.2.
For the first point, it was a typo in the readme. For the second point, I decided to remove Mashie in the last version since some API responses included a parameter `count` which is being used by Mashie. It might have triggered some instabilities, but this is now fixed.
